/**
 * Mock data for testing report generation
 */

import { ReportData } from '../reports/interfaces/report.interfaces';

/**
 * Sample report data for testing
 */
export const mockReportData: ReportData = {
  summary: {
    from: '2025-01-01T00:00:00.000Z',
    to: '2025-01-31T23:59:59.999Z',
    metricsCount: 3,
    environment: 'development',
    source: 'adt.getAllRealtimeMetrics',
    filters: { team_id: 'team-123' },
    totalUsers: 3,
    totalTimeWorked: '24:30:00',
    averageActivity: 65,
    averageProductivity: 75,
    totalActiveBeats: 15000,
    totalIdleBeats: 8000,
    totalKeyboardInputs: 50000,
    totalMouseClicks: 25000,
    mostActiveUser: { name: 'John Doe', activityPercentage: 85 },
    leastActiveUser: { name: 'Jane Smith', activityPercentage: 45 },
  },
  items: [
    {
      contractorId: 'contractor-001',
      contractorName: 'John Doe',
      jobPosition: 'Senior Developer',
      clientId: 'client-001',
      clientName: 'Acme Corp',
      teamId: 'team-001',
      teamName: 'Engineering',
      country: 'USA',
      timeWorked: '08:30:00',
      activityPercentage: 85,
      productivityScore: 92,
    },
    {
      contractorId: 'contractor-002',
      contractorName: 'Jane Smith',
      jobPosition: 'Frontend Developer',
      clientId: 'client-002',
      clientName: 'Tech Inc',
      teamId: 'team-002',
      teamName: 'Product',
      country: 'Canada',
      timeWorked: '08:00:00',
      activityPercentage: 45,
      productivityScore: 58,
    },
    {
      contractorId: 'contractor-003',
      contractorName: 'Bob Johnson',
      jobPosition: 'Backend Developer',
      clientId: 'client-003',
      clientName: 'Startup XYZ',
      teamId: 'team-001',
      teamName: 'Engineering',
      country: 'UK',
      timeWorked: '08:00:00',
      activityPercentage: 65,
      productivityScore: 75,
    },
  ],
};

/**
 * Extended mock data with more contractors
 */
export const mockReportDataExtended: ReportData = {
  summary: {
    from: '2025-01-01T00:00:00.000Z',
    to: '2025-01-31T23:59:59.999Z',
    metricsCount: 10,
    environment: 'development',
    source: 'adt.getAllRealtimeMetrics',
    filters: {},
    totalUsers: 10,
    totalTimeWorked: '80:00:00',
    averageActivity: 68,
    averageProductivity: 76,
    totalActiveBeats: 120000,
    totalIdleBeats: 48000,
    totalKeyboardInputs: 480000,
    totalMouseClicks: 240000,
    mostActiveUser: { name: 'Alice Williams', activityPercentage: 95 },
    leastActiveUser: { name: 'Charlie Brown', activityPercentage: 35 },
  },
  items: [
    {
      contractorId: 'contractor-001',
      contractorName: 'John Doe',
      jobPosition: 'Senior Developer',
      clientId: 'client-001',
      clientName: 'Acme Corp',
      teamId: 'team-001',
      teamName: 'Engineering',
      country: 'USA',
      timeWorked: '08:30:00',
      activityPercentage: 85,
      productivityScore: 92,
    },
    {
      contractorId: 'contractor-002',
      contractorName: 'Jane Smith',
      jobPosition: 'Frontend Developer',
      clientId: 'client-002',
      clientName: 'Tech Inc',
      teamId: 'team-002',
      teamName: 'Product',
      country: 'Canada',
      timeWorked: '08:00:00',
      activityPercentage: 45,
      productivityScore: 58,
    },
    {
      contractorId: 'contractor-003',
      contractorName: 'Bob Johnson',
      jobPosition: 'Backend Developer',
      clientId: 'client-003',
      clientName: 'Startup XYZ',
      teamId: 'team-001',
      teamName: 'Engineering',
      country: 'UK',
      timeWorked: '08:00:00',
      activityPercentage: 65,
      productivityScore: 75,
    },
    {
      contractorId: 'contractor-004',
      contractorName: 'Alice Williams',
      jobPosition: 'Tech Lead',
      clientId: 'client-001',
      clientName: 'Acme Corp',
      teamId: 'team-001',
      teamName: 'Engineering',
      country: 'USA',
      timeWorked: '08:30:00',
      activityPercentage: 95,
      productivityScore: 98,
    },
    {
      contractorId: 'contractor-005',
      contractorName: 'Charlie Brown',
      jobPosition: 'Junior Developer',
      clientId: 'client-004',
      clientName: 'StartupHub',
      teamId: 'team-003',
      teamName: 'Development',
      country: 'Germany',
      timeWorked: '08:00:00',
      activityPercentage: 35,
      productivityScore: 42,
    },
    {
      contractorId: 'contractor-006',
      contractorName: 'Diana Prince',
      jobPosition: 'UX Designer',
      clientId: 'client-002',
      clientName: 'Tech Inc',
      teamId: 'team-002',
      teamName: 'Product',
      country: 'USA',
      timeWorked: '08:00:00',
      activityPercentage: 72,
      productivityScore: 80,
    },
    {
      contractorId: 'contractor-007',
      contractorName: 'Ethan Hunt',
      jobPosition: 'DevOps Engineer',
      clientId: 'client-001',
      clientName: 'Acme Corp',
      teamId: 'team-004',
      teamName: 'Infrastructure',
      country: 'Canada',
      timeWorked: '08:00:00',
      activityPercentage: 78,
      productivityScore: 85,
    },
    {
      contractorId: 'contractor-008',
      contractorName: 'Fiona Green',
      jobPosition: 'QA Engineer',
      clientId: 'client-003',
      clientName: 'Startup XYZ',
      teamId: 'team-002',
      teamName: 'Product',
      country: 'UK',
      timeWorked: '08:00:00',
      activityPercentage: 68,
      productivityScore: 74,
    },
    {
      contractorId: 'contractor-009',
      contractorName: 'George Miller',
      jobPosition: 'Data Analyst',
      clientId: 'client-005',
      clientName: 'DataCorp',
      teamId: 'team-005',
      teamName: 'Analytics',
      country: 'Australia',
      timeWorked: '08:00:00',
      activityPercentage: 55,
      productivityScore: 65,
    },
    {
      contractorId: 'contractor-010',
      contractorName: 'Hannah Lee',
      jobPosition: 'Product Manager',
      clientId: 'client-002',
      clientName: 'Tech Inc',
      teamId: 'team-002',
      teamName: 'Product',
      country: 'South Korea',
      timeWorked: '08:00:00',
      activityPercentage: 82,
      productivityScore: 88,
    },
  ],
};

/**
 * Mock data for individual contractor report
 */
export const mockIndividualReportData: ReportData = {
  summary: {
    from: '2025-01-01T00:00:00.000Z',
    to: '2025-01-31T23:59:59.999Z',
    contractorId: 'contractor-001',
    metricsCount: 1,
    environment: 'development',
    source: 'adt.getRealtimeMetrics',
    filters: { contractor_id: 'contractor-001' },
    totalUsers: 1,
    totalTimeWorked: '08:30:00',
    averageActivity: 85,
    averageProductivity: 92,
    totalActiveBeats: 18000,
    totalIdleBeats: 3000,
    totalKeyboardInputs: 65000,
    totalMouseClicks: 32000,
  },
  items: [
    {
      contractorId: 'contractor-001',
      contractorName: 'Carlos Rodriguez',
      jobPosition: 'Senior Full Stack Developer',
      clientId: 'client-001',
      clientName: 'Andes Workforce',
      teamId: 'team-001',
      teamName: 'Engineering',
      country: 'Colombia',
      timeWorked: '08:30:00',
      activityPercentage: 85,
      productivityScore: 92,
    },
  ],
};
